
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-16T14:41:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f57bfebf04b6293c1a93d0ba9300184fd43b0e85",
 "version": "1.2.1-alpha.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
