# eython CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
experimental:
  pipelines: true
workflows:
  version: 2
  test-deploy:
    jobs:
      - test-3.8:
          filters:
            tags:
              only: /.*/
      - test-3.7:
          filters:
            tags:
              only: /.*/
      - test-3.6:
          filters:
            tags:
              only: /.*/
      - test-3.5:
          filters:
            tags:
              only: /.*/
      - test-3.4:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test-3.8
            - test-3.7
            - test-3.6
            - test-3.5
            - test-3.4
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
variables:
  test-template: &test-template
    docker:
      # Available CircleCI Python images: https://hub.docker.com/r/circleci/python/tags/
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - pip-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements-test.txt" }}
          # fallback to using the latest cache if no exact match is found
          - pip-cache-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements-test.txt

      - save_cache:
          paths:
            - ./venv
          key: pip-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements-test.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
      - store_artifacts:
          path: htmlcov
          destination: htmlcov

      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: htmlcov
          destination: htmlcov

      - run:
          name: send coverage to coveralls
          command: |
            . venv/bin/activate
            coveralls

jobs:
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4

  # Deploy to PyPI if semvar git tag pushed
  # https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/
  deploy:
    docker:
      # Available CircleCI Python images: https://hub.docker.com/r/circleci/python/tags/
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - pip-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements-test.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install flit

      - save_cache:
          paths:
            - ./venv
          key: pip-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements-test.txt" }}

      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            flit publish
