[tool.poetry]
name = "vegi"
version = "0.1.0"
description = "Vegetation Index Library"
authors = ["mitch3x3 <mitch3x3@github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
rasterio = "^1.1.5"
numpy = "^1.18.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
