# This file was generated automatically by filter-stubs.py

import io
import threading
import multiprocessing as mp
import urllib3
from typing import Any
from typing import BinaryIO
from typing import Callable
from typing import Iterator
from typing import List
from typing import Literal
from typing import Mapping
from typing import NamedTuple
from typing import Optional
from typing import Sequence
from typing import TYPE_CHECKING
from typing import TextIO
from typing import Tuple
from typing import Union
from typing import overload
from blobfile.common import Request
from blobfile.common import RequestFailure
class Stat(NamedTuple):
    size: int
    mtime: float
    ...

@overload
def BlobFile(path: str, mode: Literal['rb'], streaming: Optional[bool]=..., buffer_size: int=..., cache_dir: Optional[str]=...) -> BinaryIO:
  ...
@overload
def BlobFile(path: str, mode: Literal['wb'], streaming: Optional[bool]=..., buffer_size: int=..., cache_dir: Optional[str]=...) -> BinaryIO:
  ...
@overload
def BlobFile(path: str, mode: Literal['ab'], streaming: Optional[bool]=..., buffer_size: int=..., cache_dir: Optional[str]=...) -> BinaryIO:
  ...
@overload
def BlobFile(path: str, mode: Literal['r'], streaming: Optional[bool]=..., buffer_size: int=..., cache_dir: Optional[str]=...) -> TextIO:
  ...
@overload
def BlobFile(path: str, mode: Literal['w'], streaming: Optional[bool]=..., buffer_size: int=..., cache_dir: Optional[str]=...) -> TextIO:
  ...
@overload
def BlobFile(path: str, mode: Literal['a'], streaming: Optional[bool]=..., buffer_size: int=..., cache_dir: Optional[str]=...) -> TextIO:
  ...
def BlobFile(path: str, mode: Literal['r', 'rb', 'w', 'wb', 'a', 'ab']=..., streaming: Optional[bool]=..., buffer_size: int=..., cache_dir: Optional[str]=...):
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['rb'], buffer_size: int=..., cache_dir: Optional[str]=...) -> BinaryIO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['wb'], buffer_size: int=..., cache_dir: Optional[str]=...) -> BinaryIO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['ab'], buffer_size: int=..., cache_dir: Optional[str]=...) -> BinaryIO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['r'], buffer_size: int=..., cache_dir: Optional[str]=...) -> TextIO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['w'], buffer_size: int=..., cache_dir: Optional[str]=...) -> TextIO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['a'], buffer_size: int=..., cache_dir: Optional[str]=...) -> TextIO:
  ...
def LocalBlobFile(path: str, mode: Literal['r', 'rb', 'w', 'wb', 'a', 'ab']=..., buffer_size: int=..., cache_dir: Optional[str]=...):
  ...
def basename(path: str) -> str:
  ...
def configure(log_callback: Callable[[str], None]=..., connection_pool_max_size: int=...) -> None:
  ...
def copy(src: str, dst: str, overwrite: bool=..., return_md5: bool=...) -> Optional[str]:
  ...
def dirname(path: str) -> str:
  ...
def exists(path: str) -> bool:
  ...
def get_url(path: str) -> Tuple[str, Optional[float]]:
  ...
def glob(pattern: str, parallel: bool=...) -> Iterator[str]:
  ...
def isdir(path: str) -> bool:
  ...
def join(a: str) -> str:
  ...
def listdir(path: str, shard_prefix_length: int=...) -> Iterator[str]:
  ...
def makedirs(path: str) -> None:
  ...
def md5(path: str) -> str:
  ...
def remove(path: str) -> None:
  ...
def rmdir(path: str) -> None:
  ...
def rmtree(path: str) -> None:
  ...
def set_log_callback(fn: Callable[[str], None]) -> None:
  ...
def stat(path: str) -> Stat:
  ...
def walk(top: str, topdown: bool=..., onerror: Optional[Callable]=...) -> Iterator[Tuple[str, Sequence[str], Sequence[str]]]:
  ...
