[package]
name = "py-sr25519-bindings"
description = "Python bindings for sr25519 library"
authors=["openAware B.V."]
version = "0.1.2"
repository = "https://github.com/polkascan/py-sr25519-bindings"
homepage = "https://github.com/polkascan/py-sr25519-bindings"
license = "Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
schnorrkel = "0.9.1"

[dev-dependencies]
hex-literal = "0.2"

[lib]
name = "sr25519"
crate-type = ["cdylib"]

# Allows `cargo test --no-default-features` to work
# see: https://github.com/PyO3/pyo3/issues/341
[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dependencies.pyo3]
version = "0.9.2"

[package.metadata.maturin]
maintainer = "openAware B.V."
maintainer-email = "legal@openaware.com"
classifier = [
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8"
]
