
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-12T15:27:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "44a86ff252da0c1dbcbc959f5673cd8d681e3c44",
 "version": "1.15.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
