[tool.poetry]
name = "renconstruct"
version = "1.2.3"
description = "A utility script for automatically building Ren'Py applications for multiple platforms."
authors = ["CobaltCore <cobaltcore@yandex.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kobaltcore/renconstruct"
homepage = "https://github.com/kobaltcore/renconstruct"

[tool.poetry.scripts]
renconstruct = "renconstruct.renconstruct:cli"

[tool.poetry.dependencies]
python = "^3.5"
click = "^7.1.2"
pyyaml = "^5.3.1"
logzero = "^1.5.0"
tqdm = "^4.46.1"
termcolor = "^1.1.0"
renutil = "^1.11.0"
renotize = "^1.1.0"
diff-match-patch = "^20181111"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.1"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
