[tool.poetry]
name = "see137"
version = "0.0.1"
description = "The way we're to manage things like ordering, data management, portfolio tracking, etc inside of the darwin system. Ray and RL lib examples included"
authors = ["Kevin Hill <kivo360@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.8"
addict = "^2.2.1"
jamboree = "0.8.8"
PyPortfolioOpt = "^1.2.1"
pydantic = "^1.5.1"
faker = "^4.0.3"
toolz = "^0.10.0"
dask = "^2.18.1"

[tool.poetry.dev-dependencies]
pylint = "^2.5.2"
autopep8 = "^1.5.2"
wheel = "^0.34.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
