---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
      - name: message-broker
        image: {{MESSAGE_BROKER_IMAGE}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        {% set mountpoints=RMB_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        ports:
        - containerPort: 5672
          name: tcp
        - containerPort: 15672
          name: management
        env:
        {% set environment=RMB_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
      volumes:
        {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
