---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: {{REANA_SERVICE_ACCOUNT_NAME}}
      containers:
      - name: server
        image: {{SERVER_IMAGE}}
        {% if DEBUG %}
        command: ["/bin/sh","-c"]
        args: ["set -e; ./scripts/setup; invenio run -h 0.0.0.0 -p 5000"]
        tty: true
        stdin: true
        {% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        - mountPath: {{SHARED_VOLUME_PATH}}
          name: reana-shared-volume
        {% set mountpoints=RS_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        ports:
        - containerPort: 5000
          name: http
        env:
        {% if REANA_URL %}
        - name: REANA_URL
          value: {{REANA_URL}}
        {% endif %}
        {% set environment=RS_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
        {% if not DEBUG %}
        - name: REANA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: user
        - name: REANA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: password
        - name: CERN_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: reana-cern-sso-secrets
              key: CERN_CONSUMER_KEY
        - name: CERN_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: reana-cern-sso-secrets
              key: CERN_CONSUMER_SECRET
        - name: REANA_GITLAB_OAUTH_APP_ID
          valueFrom:
            secretKeyRef:
              name: reana-cern-gitlab-secrets
              key: REANA_GITLAB_OAUTH_APP_ID
        - name: REANA_GITLAB_OAUTH_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: reana-cern-gitlab-secrets
              key: REANA_GITLAB_OAUTH_APP_SECRET
        - name: REANA_GITLAB_HOST
          valueFrom:
            secretKeyRef:
              name: reana-cern-gitlab-secrets
              key: REANA_GITLAB_HOST
        {% endif %}
      - name: scheduler
        image: {{SERVER_IMAGE}}
        command: ["flask", "start-scheduler"]
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        - mountPath: {{SHARED_VOLUME_PATH}}
          name: reana-shared-volume
        {% set mountpoints=RS_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        env:
        {% set environment=RS_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
        {% if not DEBUG %}
        - name: REANA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: user
        - name: REANA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: password
        {% endif %}
      volumes:
      - name: reana-shared-volume
        {% if CEPHFS %}
        persistentVolumeClaim:
          claimName: manila-cephfs-pvc
          readOnly: false
        {% else %}
        hostPath:
          path: {{ROOT_PATH}}
        {% endif %}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
