---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccountName: {{REANA_SERVICE_ACCOUNT_NAME}}
      containers:
      - name: rest-api-server
        image: {{WORKFLOW_CONTROLLER_IMAGE}}
        {% if DEBUG %}
        command: ["/bin/sh","-c"]
        args: ["flask run --host=0.0.0.0"]
        tty: true
        stdin: true
        {% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        - mountPath: {{SHARED_VOLUME_PATH}}
          name: reana-shared-volume
        {% set mountpoints=RWFC_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: K8S_REANA_SERVICE_ACCOUNT_NAME
          value: {{REANA_SERVICE_ACCOUNT_NAME}}
        {% if REANA_URL %}
        - name: REANA_URL
          value: {{REANA_URL}}
        {% endif %}
        {% if EOS %}
        - name: K8S_CERN_EOS_AVAILABLE
          value: "True"
        {% endif %}
        - name: REANA_DEPLOYMENT_TYPE
          value: {{DEPLOYMENT}}
        {% if CEPHFS %}
        - name: REANA_STORAGE_BACKEND
          value: "cephfs"
        {% endif %}
        {% set environment=RWFC_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
        {% if not DEBUG %}
        - name: REANA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: user
        - name: REANA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: password
        - name: REANA_GITLAB_HOST
          valueFrom:
            secretKeyRef:
              name: reana-cern-gitlab-secrets
              key: REANA_GITLAB_HOST
        {% endif %}
      - name: job-status-consumer
        image: {{WORKFLOW_CONTROLLER_IMAGE}}
        command: ["flask", "consume-job-queue"]
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        - mountPath: {{SHARED_VOLUME_PATH}}
          name: reana-shared-volume
        {% set mountpoints=RWFC_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        env:
        {% if REANA_URL %}
        - name: REANA_URL
          value: {{REANA_URL}}
        {% endif %}
        {% set environment=RWFC_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
        {% if not DEBUG %}
        - name: REANA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: user
        - name: REANA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: password
        {% endif %}
      volumes:
      - name: reana-shared-volume
        {% if CEPHFS %}
        persistentVolumeClaim:
          claimName: manila-cephfs-pvc
          readOnly: false
        {% else %}
        hostPath:
          path: {{ROOT_PATH}}
        {% endif %}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
