# https://pre-commit.com/
repos:
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761  # Must match ci/requirements/*.yml
    hooks:
      - id: mypy
        files: hydrodata

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.22.1
    hooks:
      - id: pyupgrade
        args:
          - "--py36-plus"
