[tool.poetry]
name = "stepped-augustus"
version = "1.0.0"
description = "A variation of the Augustus Cipher that offsets space-separated words based on the position of each character."
authors = ["PureFunctor <purefunctor@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["augustus", "cipher"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Topic :: Security :: Cryptography"
]
packages = [
    { include = "augustus" }
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.4.3"

[tool.poetry.scripts]
augustus = "augustus.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
