[tool.poetry]
name = "s3-kvs"
version = "0.1.3"
description = "Python wrapper for an AWS S3 backed key-value store."
authors = ["Richard Campen <richard@campen.co>"]
readme = 'README.rst'
homepage = 'https://github.com/octavenz/s3-kvs'
license = 'MIT'

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
