DIRECTORY: T:\Group\CI\Research AI request_PRIP projects\Project Creator
PROJECT: Activation Energy
TOPICS:
- VGPG
- PG
- VG
- VGPG-Nic2
- VGPG-Nic2-Water20
- VGPG-Nic2-Water20-LacAcid4
- VGPG-Nic2-LacAcid4
GRADIENTS:
- 10
- 15
- 20
- 25
- 30
- 35
- 40
ISOTHERMS:

TECHNIQUES:
- STA
- MS
- TG
