[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "contxt-sdk"
version = "1.0.0-beta.15"
description = "Contxt SDK from </ndustrial.io>"
authors = ["ndustrial.io <dev@ndustrial.io>"]
license = "ISC"
readme = "README.md"
repository = "https://github.com/ndustrialio/contxt-sdk-python"
packages = [ { include = "contxt" } ]

[tool.poetry.dependencies]
python = "^3.6"
auth0-python = "^3"
dataclasses = { version = "*", python = "<3.7" }
pyjwt = { version = "^1", extras = ["crypto"] }
requests = "^2"
tabulate = "*"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8"
isort = "^4.3"
mypy = "^0.780"
pytest = "^5.0"

[tool.poetry.scripts]
contxt = "contxt.__main__:cli"

[tool.black]
line-length = 105

[tool.isort]
line_length = 105
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
