NODE_MODELS = {
    'acso': "A10 Networks - ACOS",
    'aen': 'Accedian',
    'adtran': 'Adtran - Total Access AOS',
    'aos': 'Alcatel-Lucent - AOS',
    'aos7':'Alcatel-Lucent - AOS7',
    'isam': 'Alcatel-Lucent - ISAM',
    'sros': 'Alcatel-Lucent - SROS (TiMOS)',
    'awplus': 'Allied Telesis - Alliedware Plus',
    'powerconnect': 'Allied Telesis - AT8000(G)S',
    'alvarion': 'Alvarion - BreezeACCESS',
    'apc_aos': 'APC - AOS',
    'arbos': 'Arbor Networks - ArbOS',
    'eos': 'Arista - EOS',
    'c4cmts': 'Arris - C4CMTS',
    'aosw': 'Aruba - AOSW',
    'audiocodes': 'Audiocodes',
    'audiocodesmp': 'Audiocodes - MediaPack',
    'voss': 'Avaya - VOSS',
    'boss': ' Avaya - BOSS',
    'fabricos': 'Brocade - FabricOS',
    'fastiron': 'Brocade - FastIron',
    'ironware': 'Brocade - IronWare',
    'nos': 'Brocade - NOS',
    'vyatta': 'Brocade - Vyatta',
    'br6910': 'Brocade - 6910',
    'slxos': 'Brocade - SLX-OS',
    'axos': 'Calix - AXOS',
    'cambium': 'Cambium - PMP450 Series',
    'casa': 'Casa',
    'cnos': 'Centec Netowrks - CNOS',
    'gaiaos': 'Checkpoint - GaiaOS',
    'saos': 'Ciena - SAOS',
    'acsw': 'Cisco - ACSW',
    'aireos': 'Cisco - AireOS',
    'asa': "Cisco - ASA",
    'asyncos': 'Cisco - AsyncOS',
    'catos': 'Cisco CatOS',
    'firelinuxos': 'Cisco - FireLinuxOS',
    'ios': "Cisco - IOS",
    'iosxe': "Cisco - IOSXE",
    'iosxr': "Cisco - IOSXR",
    'cisconga': 'Cisco - NGA',
    'nxos': "Cisco - NXOS",
    'ciscosma': 'Cisco - SMA',
    'ciscosmb': 'Cisco - SMB',
    'ucs': ' Cisco - UCS',
    'ciscovpn3k': 'Cisco VPN 3000',
    'netscaler': 'Citrix Netscaler (Virtual)',
    'corianttmos': 'Coriant - TMOS (8800)',
    'coriant8600': 'Coriant - 8600',
    'coriantgroove': ' Coriant - Groove',
}