[tool.poetry]
name = "forex-types"
version = "0.0.6"
description = "Basic Forex Classes"
authors = ["Andrew Allaire <andrew.allaire@gmail.com>"]
license = "MIT"
repository = "https://github.com/aallaire/python_forex_types"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
