# Generated by Django 2.2.4 on 2019-09-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_auto_20190821_2122'),
        ('election', '0003_election_ap_election_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Generally, only used for the presidency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to='geography.Division'),
        ),
    ]
