# Generated by Django 3.0.2 on 2020-01-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20200116_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionballot',
            name='party_reaffiliation_deadline_independent_voters',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionballot',
            name='party_reaffiliation_deadline_other_party_voters',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionballot',
            name='voters_register_by_party',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionballot',
            name='voting_reaffiliates_automatically',
            field=models.SlugField(blank=True, choices=[('yes', 'Yes'), ('yes-unless-immediate-petition', 'Yes (unless voters file a petition when registering)'), ('no', 'No')], null=True),
        ),
        migrations.AddField(
            model_name='electionballot',
            name='who_can_vote',
            field=models.SlugField(blank=True, choices=[('only_party_members', 'Only party members'), ('party_members_and_independents', 'Party members & independents'), ('all_voters', 'All voters')], null=True),
        ),
    ]
