# Generated by Django 3.0.3 on 2020-02-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0018_candidateelection_ballot_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='race_type_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
