# Generated by Django 3.0.3 on 2020-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0021_auto_20200222_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='division_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
