# Generated by Django 2.2.6 on 2019-10-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_race_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='electoral_votes',
            field=models.IntegerField(blank=True, help_text='The number of presidential electors this area awards.', null=True),
        ),
    ]
