# Generated by Django 3.0.2 on 2020-01-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20200115_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionballot',
            name='election_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='election.ElectionEvent'),
        ),
    ]
