# Generated by Django 3.0.2 on 2020-01-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20200115_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionballot',
            name='overall_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
