# Generated by Django 3.0.2 on 2020-02-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20200208_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiontype',
            name='slug',
            field=models.SlugField(blank=True, choices=[('general', 'General election'), ('partisan-caucus', 'Caucus'), ('partisan-firehouse-caucus', 'Firehouse Caucus'), ('partisan-primary', 'Primary'), ('primary-runoff', 'Primary Runoff'), ('general-runoff', 'General Runoff'), ('top-two-primary', 'Top-two Primary'), ('majority-elects-blanket-primary', 'Majority-elects blanket primary')], max_length=255, unique=True),
        ),
    ]
