# Generated by Django 3.0.3 on 2020-02-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0019_election_race_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='national_delegates_awarded',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Generally, only used for the presidency.', null=True),
        ),
    ]
