[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"


[tool.flit.metadata]
module = "desktopography"
author = "Fabien Bochu"
author-email = "fabien.bochu+desktopography@gmail.com"
home-page = "https://gitlab.com/fbochu/desktopography"
keywords="desktopography, wallpapers"
description-file = "README.md"
license="BSD"
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: X11 Applications',
    'Intended Audience :: End Users/Desktop',
    'License :: OSI Approved :: BSD License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Topic :: Desktop Environment',
    'Topic :: Utilities',
]

requires-python = ">=3.7"
requires = [
    'BeautifulSoup4',
    'click',
    'daiquiri',
    'requests',
]

[tool.flit.metadata.requires-extra]
dev = [
    "isort[pyproject]",
    "prospector",
]

[tool.flit.scripts]
desktopography = "desktopography.cli:main"

[tool.isort]
force_single_line = true
force_sort_within_sections = true

[tool.flake8]
max-line-length = 120
exclude = "build,dist,venv"
max-complexity = 10
