[tool.poetry]
name = "discord-rebot"
version = "0.0.2"
description = "RegEx based command mapping discord BOT framework with authorization"
license = "MIT"
authors = ["nkpro2000sr <srnaveen2k@yahoo.com>"]
maintainers = ["nkpro2000sr <srnaveen2k@yahoo.com>"]
readme = "README.md"
repository = "https://github.com/nkpro2000sr/discord-rebot"
documentation = "https://discord-rebot.readthedocs.io/en/latest/"
packages = [
    { include = "discordRebot", from = "src" },
]
keywords = ["discord","rebot","regex","tryrebot"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.3.3"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-asyncio = "^0.12.0"
dpytest = "^0.0.20"
sphinx = "^3.1.0"
groundwork-sphinx-theme = "^1.1.1"
sphinx-autodoc-typehints = "^1.10.3"

[tool.black]
line-length = 99
target-version = ['py38']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
