
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-11T16:14:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e42aeb0d4693b2ce43900521096d2b5589e4adab",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
