# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_auto_20160715_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='action time'),
        ),
        migrations.AlterField(
            model_name='log',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True, verbose_name='object id'),
        ),
    ]
