[tool.poetry]
name = "polecat-auth"
version = "0.0.1"
description = ""
authors = ["Luke Hodkinson <furious.luke@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
polecat = "*"

[tool.poetry.dev-dependencies]
pytest-polecat = "*"
