- job:
    name: barbican-devstack-functional-base
    parent: legacy-dsvm-base
    vars:
      database: sql
      python_version: py36
      services: tempest,rabbit,mysql,key
    required-projects:
      - openstack/devstack-gate
      - openstack/barbican
      - openstack/barbican-tempest-plugin
      - openstack/python-barbicanclient
    run: playbooks/legacy/barbican-devstack-functional-base/run.yaml
    post-run: playbooks/legacy/barbican-devstack-functional-base/post.yaml
    timeout: 4200

- job:
    name: barbican-devstack-base
    parent: legacy-base
    vars:
      database: sql
      python_version: py27
      services: tempest,keystone
    required-projects:
      - openstack/devstack
      - openstack/devstack-gate
      - openstack/barbican
      - openstack/barbican-tempest-plugin
      - openstack/python-barbicanclient
    run: playbooks/legacy/barbican-devstack-base/run.yaml
    post-run: playbooks/legacy/barbican-devstack-base/post.yaml
    timeout: 4200

- job:
    name: barbican-devstack-tempest-base
    parent: legacy-dsvm-base
    vars:
      python_version: py27
      database: sql
      castellan_from_git: 0
      cursive: 0
    required-projects:
      - openstack/devstack-gate
      - openstack/barbican
      - openstack/barbican-tempest-plugin
      - openstack/castellan
      - x/cursive
      - openstack/python-barbicanclient
      - openstack/tempest
    run: playbooks/legacy/barbican-devstack-tempest-base/run.yaml
    post-run: playbooks/legacy/barbican-devstack-tempest-base/post.yaml
    timeout: 4200

- job:
    name: barbican-dogtag-devstack-functional-fedora-latest
    nodeset: devstack-single-node-fedora-latest
    parent: barbican-devstack-functional-base
    # non-voting until https://pagure.io/dogtagpki/issue/3108 is fixed
    voting: false
    vars:
      python_version: py35
      services: barbican-dogtag,tempest,rabbit,mysql,key
      plugin: dogtag
    post-run: playbooks/legacy/barbican-devstack-functional-base/dogtag-post.yaml

- job:
    name: barbican-vault-devstack-functional
    parent: barbican-devstack-functional-base
    vars:
      services: barbican-vault,tempest,rabbit,mysql,key
      plugin: vault

- job:
    name: barbican-kmip-devstack-functional
    parent: barbican-devstack-functional-base
    vars:
      services: barbican-pykmip,pykmip-server,tempest,rabbit,mysql,key
      plugin: kmip

- job:
    name: barbican-simple-crypto-devstack-functional
    parent: barbican-devstack-functional-base
    vars:
      plugin: simple-crypto

- job:
    name: barbican-simple-crypto-devstack-functional-postgres
    parent: barbican-devstack-functional-base
    voting: false
    vars:
      database: postgres
      plugin: simple-crypto

- job:
    name: barbican-dogtag-devstack-fedora-latest
    nodeset: devstack-single-node-fedora-latest
    parent: barbican-devstack-base
    vars:
      services: barbican-dogtag,tempest,keystone
      plugin: dogtag

- job:
    name: barbican-simple-crypto-devstack
    parent: barbican-devstack-base
    vars:
      plugin: simple-crypto

- job:
    name: barbican-simple-crypto-devstack-postgres
    parent: barbican-devstack-base
    voting: false
    vars:
      plugin: simple-crypto
      database: postgres

- job:
    name: barbican-simple-crypto-devstack-tempest
    parent: barbican-devstack-tempest-base

- job:
    name: barbican-simple-crypto-devstack-tempest-castellan-from-git
    parent: barbican-devstack-tempest-base
    vars:
      castellan_from_git: 1

- job:
    name: barbican-simple-crypto-devstack-tempest-cursive
    parent: barbican-devstack-tempest-base
    vars:
      cursive: 1

- job:
    name: barbican-grenade-devstack
    parent: legacy-dsvm-base
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    run: playbooks/legacy/grenade-devstack-barbican/run.yaml
    post-run: playbooks/legacy/grenade-devstack-barbican/post.yaml
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/barbican
      - openstack/barbican-tempest-plugin
      - openstack/python-barbicanclient
    timeout: 7800

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - barbican-simple-crypto-devstack-tempest
        - barbican-simple-crypto-devstack-functional
        - barbican-simple-crypto-devstack-functional-postgres
        - barbican-dogtag-devstack-functional-fedora-latest
        - barbican-vault-devstack-functional
        - barbican-grenade-devstack
        # TripleO jobs that deploy Barbican.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario002-standalone will
        # run in Pike and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario002-standalone:
            voting: false
        - octavia-v2-dsvm-tls-barbican:
            voting: false
    gate:
      queue: barbican
      jobs:
        - barbican-simple-crypto-devstack-tempest
        - barbican-simple-crypto-devstack-functional
        # TODO(redrobot): add this back once job is voting again
        #- barbican-dogtag-devstack-functional-fedora-latest
        - barbican-vault-devstack-functional
        - barbican-grenade-devstack
    experimental:
      jobs:
        - barbican-kmip-devstack-functional

