[tool.poetry]
name = "iauditor_reporting_tool"
version = "0.1.1"
description = "A tool for exporting iAuditor inspections into human readable Excel or CSV files."
authors = ["Edd <edward.abrahamsen-mills@safetyculture.io>"]
packages = [
    { include = "modules", from = "iauditor_reporting_tool"},
    { include = "csvexporter.py", from = "iauditor_reporting_tool"}
]
[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
unicodecsv = "^0.14.1"
pandas = "^1.0.4"
OrderedDict = "^1.1"
tqdm = "^4.46.1"
xlsxwriter = "^1.2.9"
typer = "^0.2.1"
pyinquirer = "^1.0.3"
dateparser = "^0.7.6"
typer-cli = "^0.0.9"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
iauditor_reporting_export = "csvexporter:export"
iauditor_reporting_setup = "csvexporter:interactive_setup"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
