- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-horizon
      - openstack-lower-constraints-jobs
      - openstack-python-jobs-horizon
      - openstack-python3-train-jobs-horizon
