[tool.poetry]
name = "graia-protocol-core"
version = "0.0.1"
description = "Abstract implementation of \"Protocol\" in \"Graia Framework\""
authors = ["Chenwe-i-lin <1846913566@qq.com>"]
license = "AGPL-3.0"
packages = [
    { include = "graia", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "^1.5.1"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
devtools = "^0.5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
