[tool.poetry]
name = "vkstartiii"
version = "1.0.0"
description = ""
authors = ["LooPeKa <loudmaks10@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
vk_api = "^11.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
