apiVersion: v1
kind: Pod
metadata:
  name: dask-pod
  labels:
    dask: worker-pod
spec:
  restartPolicy: Never
  containers:
    - image: daskdev/dask:latest
      imagePullPolicy: IfNotPresent
      args: [dask-worker, --nthreads, '2', --no-dashboard, --memory-limit, 6GB, --death-timeout, '600000']
      name: dask
      env:
        - name: EXTRA_PIP_PACKAGES
          value: git+https://github.com/dask/distributed moksh-orchestrator
      resources:
        limits:
          cpu: "2"
          memory: 6G
        requests:
          cpu: "2"
          memory: 6G