
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-15T15:58:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "18646939c259042669e26a22c8d2b23ac04adfd9",
 "version": "0.1.13a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
