[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "uploadabletest"
author = "Thomas Kluyver"
author-email = "thomas@kluyver.me.uk"
home-page = "https://example.com/"

