[tool.poetry]
name = "boringit"
version = "0.1.0"
description = "A tool to optimize git Add, Commit and Push routine."
authors = ["marcusmello <marcus@vintem.tech>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/marcusmello/boringit"
repository = "https://gitlab.com/marcusmello/boringit"
keywords = ["git", "git flow", "productivity"]

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
boringit = 'boringit.boringit:main'
