[tool.poetry]
name = "modetool"
version = "0.1.0"
description = ""
authors = ["Chris Coughlan <chris@coughlan.io>"]

[tool.poetry.dependencies]
python = "^3.8"
py7zr = "^0.7.3"
loguru = "^0.5.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[tool.poetry.scripts]
modetool = "modetool.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
