[tool.poetry]
name = "arcane-secret"
version = "0.2.0"
description = "A package to encode or decode tokens"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
# arcane-core = "0.1.1" (optional)

pycryptodome = "^3.9.7"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
