# The # should be replaced with the
# manila share ID and share access ID
# obtained when creating them
# following the instructions in:
# https://clouddocs.web.cern.ch/clouddocs/containers/tutorials/cephfs.html

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{CEPHFS_STORAGECLASS}}
provisioner: manila-provisioner
parameters:
  type: "Geneva CephFS Testing"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  {% if CEPHFS_OS_SHARE_ID and CEPHFS_OS_SHARE_ACCESS_ID %}
  osShareID: {{CEPHFS_OS_SHARE_ID}}
  osShareAccessID: {{CEPHFS_OS_SHARE_ACCESS_ID}}
  {% endif %}
