[tool.poetry]
name = "bart-datasets"
packages = [ 
    { include="bartdatasets", from="." }
]
version = "0.1.2"
description = ""
authors = ["Cesar Augusto <cesarabruschetta@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6.1,<3.7"
s3fs = "^0.4.2"
pyarrow = "^0.17.1"
google-api-python-client = "1.9.1"

[tool.poetry.dev-dependencies]
pandas = "^1.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
