---
- name: create openvpn client directory
  hosts: localhost
  become: false

  tasks:
    - name: mkdir -p {{ openvpn_local_directory }}
      file:
        state: directory
        path: "{{ openvpn_local_directory }}"

- name: create openvpn clients
  hosts: openvpn-service-group
  become: true

  tasks:
    - name: /etc/openvpn/easy-rsa/create-client.sh
      shell: |
        set -ex
        if ! test -d /etc/openvpn/keys/{{ item }} ; then
           /etc/openvpn/easy-rsa/create-client.sh {{ item }}
        fi
      loop: "{{ openvpn_active_clients }}"

    - name: copy client credentials locally
      fetch:
        src: "/etc/openvpn/keys/{{ item }}.tar.gz"
        dest: "{{ openvpn_local_directory }}/{{ item }}.tar.gz"
        flat: yes
      loop: "{{ openvpn_active_clients }}"
