
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-18T22:58:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a467b3aa7cee770533cc38521ff3cde84dd5c1e",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
