[tool.poetry]
name = "rpa-framework"
version = "0.0.0.0.1"
description = "Deprecated project. Current project is rpaframework."
authors = [
	"RPA Framework <rpafw@robocorp.com>",
]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
