[tool.poetry]
name = "mdfl"
version = "0.3"
description = "A prototype command-line tool for creating datapacks."
authors = ["Jeremiah Boby <mail@jeremiahboby.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
docopt = "^0.6.2"
lark-parser = "^0.8.6"
cookiecutter = "^1.7.2"

[tool.poetry.scripts]
mdfl = "mdfl:main"


[tool.poetry.dev-dependencies]
ipython = "^7.15.0"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
