
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-20T15:15:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d41dfb92d1f6d40eac40da5ea5d6d4506101015f",
 "version": "2.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
