[tool.poetry]
name = "mudkip"
version = "0.3.2"
description = "A friendly Sphinx wrapper"
authors = ["Valentin Berlier <berlier.v@gmail.com>"]
license = "MIT"

homepage = "https://github.com/vberlier/mudkip"
repository = "https://github.com/vberlier/mudkip"
documentation = "https://github.com/vberlier/mudkip"

readme = "README.md"

keywords = [
]

[tool.poetry.dependencies]
python = "^3.7"
sphinx = "^3.1.1"
click = "^7.0"
recommonmark = "^0.6.0"
watchdog = "^0.10.2"
sphinx-autodoc-typehints = "^1.6"
sphinx_rtd_theme = "^0.4.3"
livereload = "^2.6"
tomlkit = "^0.6.0"
nbsphinx = "^0.6.0"
jupyter = "^1.0"
jupyter_nbextensions_configurator = "^0.4.1"

[tool.poetry.dev-dependencies]
black = { version = "^19.10b0", allow-prereleases = true }

[tool.poetry.scripts]
mudkip = 'mudkip.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
