[tool.poetry]
name = "pyutok"
version = "1.1.0"

description = "Inspired by a tool I can not find anymore on the internet: utok 1.5. I use it to clean up path settings in large shell script configuration setups."

packages = [
    { include = "utok.py" },
]

authors = ["Berthold Höllmann <berhoel@gmail.com>"]
license = "MIT"

repository = "https://gitlab.com/berhoel/python/pyutok.git"
homepage = "https://python.xn--hllmanns-n4a.de/utok/"
documentation = "https://www.xn--hllmanns-n4a.de/utok/"
readme = "README.rst"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators",
    "Operating System :: POSIX",
    "Topic :: System :: Shells",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^2.7 || >3.5"
sphinx-argparse = "^0.2.5"

[tool.poetry.dev-dependencies]
pytest = [
    {version="^5.4.0", python=">=3.6"},
    {version="^4.6", python="^2.7"}
]
tox = "^3.15.1"
pdbpp = "^0.10.2"
Sphinx = [{version="^3.1.0", python=">=3.6"}]
sphinx-rtd-theme = [{version="^0.4.3", python=">=3.6"}]
blacker = [{ version="^0.1.0", python=">=3.6"}]
flake8 = "^3.8.2"
pylint = [{version="^2.5.2", python=">=3.5"}]
rope = "^0.17.0"
numpydoc = [{version="^1.0.0", python=">=3.6"}]
urllib3 = [{version="*", python=">=3.6"}]
pathlib2 = [
    {version="^2.3.5", python="^2.7"}
]

[tool.poetry.scripts]
utok = 'utok:main'

[tool.isort]
multi_line_output = 5
include_trailing_comma = true
use_parentheses = true
indent = '    '
length_sort = true
line_length = 88
use_parantheses = true
balanced_wrapping = true
import_heading_stdlib = 'Standard libraries.'
import_heading_thirdparty = 'Third party libraries.'
known_first_party = ['berhoel']

[flake8]
max-line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
