__version__ = '0.0.14'
__title__ = 'zwnlp'
__description__ = 'Personal NLP task utils.'
__url__ = 'https://github.com/njzhaowei/zwnlp'
__author__ = 'Zhao Wei'
__author_email__ = 'yewberry@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Zhao Wei'