
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-15T18:06:36+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8df27ffab1d71395924dcc7c2e6abfed3d4f51da",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
