[tool.poetry]
name = "ccpp-test"
version = "0.1.0"
description = ""
authors = ["guaifish <guaifish@hotmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/guaifish/ccpp-test"

include=["ccpp_test"]


[tool.poetry.dependencies]
python = "^3.6"
fire = "^0.3.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
ccpp-test = "ccpp_test.main:main"