DIRECTORY: C:\Users\mjaquier\PycharmProjects\AIdirectory\aidirectory
PROJECT: DESCRIPTIVE PROJECT TITLE
TOPICS:
- TANGO
- VOYAGER
- APOSTOLIC
- UNICORN
- Happy
GRADIENTS:
- 10
ISOTHERMS:
- 190
- 220
- 350
TECHNIQUES:
- STA
- IR
- GC
- MS
- uv
- TG
