# Generated by Django 2.2.13 on 2020-06-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrivialShippingRateProcessor',
            fields=[
                ('shippingrateprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipping.ShippingRateProcessor')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('shipping.shippingrateprocessor',),
        ),
    ]
