[tool.poetry]
name = "file-util"
version = "0.1.6"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/eyalev/file-util"

[tool.poetry.dependencies]
python = "^3.6"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
