[tool.poetry]
name = "whatsappguru"
version = "0.1.0"
description = ""
authors = ["Lorenzo Coacci <lorenzo@coacci.it>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.5"
emoji = "^0.5.4"

[tool.poetry.dev-dependencies]
pytest = "^3.7"
