---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{CEPHFS_VOLUME_SIZE}}G
  storageClassName: {{CEPHFS_STORAGECLASS}}
