[tool.poetry]
name = "dlna-cli"
version = "0.1.0"
description = ""
authors = ["Daniel Daniels <danields761@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.5.1"
click = "^7.1.2"
colorama = "^0.4.3"
termcolor = "^1.1.0"
upnpclient = "^0.0.8"
stringcase = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
