language: python
python:
  - 2.7
  - 3.7
  - pypy2.7-6.0
  - pypy3.5
  - pypy3.6-7.1.1
  - 3.5
  - 3.6
install:
  - travis_retry pip install coveralls
  - travis_retry pip install tox-travis
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install cryptography~=1.3.4 pyOpenSSL~=16.2.0; fi
script:
  tox
after_success:
  coveralls
