[tool.poetry]
name = "twinthread"
version = "0.5.0"
description = ""
authors = ["Brent Baumgartner"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"
pandas = "^1.0.4"
azure-storage-blob = "^12.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
