# coding: utf-8

"""
    Unofficial Degiro API

    Unofficial Degiro API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import degiro_client
from models.one_ofinline_response200 import OneOfinlineResponse200  # noqa: E501
from degiro_client.rest import ApiException


class TestOneOfinlineResponse200(unittest.TestCase):
    """OneOfinlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfinlineResponse200(self):
        """Test OneOfinlineResponse200"""
        # FIXME: construct object with mandatory attributes with example values
        # model = degiro_client.models.one_ofinline_response200.OneOfinlineResponse200()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
