# coding: utf-8

"""
    Unofficial Degiro API

    Unofficial Degiro API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import degiro_client
from models.config_response_data import ConfigResponseData  # noqa: E501
from degiro_client.rest import ApiException


class TestConfigResponseData(unittest.TestCase):
    """ConfigResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigResponseData(self):
        """Test ConfigResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = degiro_client.models.config_response_data.ConfigResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
