- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - neutronclient-functional
    gate:
      jobs:
        - neutronclient-functional
    experimental:
      jobs:
        - legacy-grenade-dsvm-neutron-libs:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

- job:
    name: neutronclient-functional
    parent: devstack-tox-functional
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    required-projects:
      - openstack/python-neutronclient
      - openstack/neutron
      - openstack/neutron-vpnaas
    vars:
      tox_envlist: functional
      devstack_services:
        # NOTE: neutronclient.tests.functional.base.ClientTestBase does not
        # support HTTPS endpoints now, so tls-proxy needs to be disabled.
        tls-proxy: false
      devstack_localrc:
        USE_PYTHON3: true
        LIBS_FROM_GIT: python-neutronclient
      devstack_plugins:
        neutron-vpnaas: https://opendev.org/openstack/neutron-vpnaas
