[tool.poetry]
name = "simplelanscan"
version = "0.1.9"
description = "Python Script to scan the local lan, report back the clients currently connected, and push to ElasticSearch."
authors = ["blcarlson01"]
license = "MIT"
include = ["lanscan/config.ini","lanscan/index.json","scan_lan_clients.service"]
documentation = "https://github.com/blcarlson01/simplelanscan"
repository = "https://github.com/blcarlson01/simplelanscan"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
elasticsearch = "^7.0.0"
scapy = "2.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
simplelanscan = 'simplelanscan.scan:run_scan'

[tool.poetry.urls]
issues = "https://github.com/blcarlson01/simplelanscan/issues"