[tool.poetry]
name = "os-util"
version = "0.1.1"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]
repository = 'https://github.com/eyalev/os-util'
readme = "README.md"

[tool.poetry.scripts]
os-util = "os_util.cli:cli"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
shell-util = "^0.1.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
