language: python

matrix:
    include:
        - os: linux
          python: 3.6
        - os: osx
          osx_image: xcode10
          language: generic

#compiler:
#  - gcc
#  - clang
# On OS X, gcc is an alias for clang s. https://docs.travis-ci.com/user/languages/c/#gcc-on-os-x

env:
  global:
    - SWMM_HOME=`pwd`
    - BUILD_HOME=build
    - RELEASE_HOME=release
    - TEST_HOME=nrtestsuite
    - SWMM_VERSION=""
    - GIT_RELEASE_DIR=GIT_RELEASE

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install libomp ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update ;
      sudo apt-get install -y libboost-test-dev ;
      sudo apt-get install -y swig ;
    fi

#install:

before_script:
  - mkdir -p $BUILD_HOME
  - mkdir -p $RELEASE_HOME

script:

  - cd $BUILD_HOME

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake ../ -DBUILD_TESTS=ON -DBUILD_COVERAGE=ON .. ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake ../ -DBUILD_TESTS=ON .. ;
    fi

  - cmake --build .
  # run unit tests
  - cd tests
  - ctest
  - cd $SWMM_HOME
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install --src build/packages -r tools/requirements.txt ;
      tools/before-test.sh $TEST_HOME $SWMM_HOME/$BUILD_HOME/bin $TRAVIS_COMMIT ;
      tools/run-nrtest.sh -c -t $TEST_HOME -v $TRAVIS_COMMIT ;
    fi
  - cd $SWMM_HOME
  
  
deploy:
  provider: releases
  api_key: $OWA_SWMM_CI_TOKEN
  file: 
    - "$SWMM_HOME/OWA-SWMM-$TRAVIS_OS_NAME-$SWMM_VERSION.zip"
  skip_cleanup: true
  overwrite: true 
  draft: true 
  on:
    branch: develop
    tag: true 
  
after_success:
  - cd $SWMM_HOME 
  - cd $RELEASE_HOME
  - cmake ../
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake ../ -DBUILD_TESTS=OFF -DBUILD_COVERAGE=OFF .. ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake ../ -DBUILD_TESTS=OFF .. ;
    fi
  - cmake --build . --config Release
  - ls -l $SWMM_HOME/$RELEASE_HOME/
  - cd $SWMM_HOME
  - SWMM_VERSION=$($SWMM_HOME/$RELEASE_HOME/bin/run-swmm --version 2>&1)
  - SWMM_VERSION="$(echo -e "${SWMM_VERSION}" | sed -n -e 'H;${x;s/\n//g;p;}')"
  - echo $SWMM_VERSION
  - mkdir $GIT_RELEASE_DIR
  - mkdir $GIT_RELEASE_DIR/$TRAVIS_OS_NAME
  - mkdir $GIT_RELEASE_DIR/$TRAVIS_OS_NAME/"lib" 
  - mkdir $GIT_RELEASE_DIR/$TRAVIS_OS_NAME/"bin" 
  - mkdir $GIT_RELEASE_DIR/$TRAVIS_OS_NAME/"include" 
  - cp $SWMM_HOME/$RELEASE_HOME/lib/* $GIT_RELEASE_DIR/$TRAVIS_OS_NAME/"lib"
  - cp $SWMM_HOME/$RELEASE_HOME/bin/run-swmm $GIT_RELEASE_DIR/$TRAVIS_OS_NAME/"bin"
  - cp $SWMM_HOME/include/* $GIT_RELEASE_DIR/$TRAVIS_OS_NAME/"include"
  - echo "OWA-SWMM-$TRAVIS_OS_NAME-$SWMM_VERSION.zip"
  - cd $GIT_RELEASE_DIR/$TRAVIS_OS_NAME
  - zip -r "../../OWA-SWMM-$TRAVIS_OS_NAME-$SWMM_VERSION.zip" ./lib/ ./bin/ ./include/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      bash <(curl -s https://codecov.io/bash) ;
    fi