---
apiVersion: v1
kind: Service
metadata:
  name: workflow-controller
spec:
  type: "NodePort"
  ports:
  - port: 80
    targetPort: 5000
    name: "http"
    protocol: TCP
  selector:
    app: workflow-controller
