# Generated by Django 3.0.6 on 2020-06-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('customers', '0001_initial'),
        ('viewflow', '0008_jsonfield_and_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Person', verbose_name='személyes adatok')),
            ],
            options={
                'verbose_name': 'alkalmazott',
                'verbose_name_plural': 'alkalmazottak',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('current_month', models.PositiveSmallIntegerField(verbose_name='tárgyhó')),
                ('current_year', models.PositiveIntegerField(verbose_name='tárgyév')),
                ('submitted', models.NullBooleanField(help_text='hatóság felé elküldve', verbose_name='elküldve')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.Employee', verbose_name='alkalmazott')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='foglalkoztató')),
            ],
            options={
                'verbose_name': 'bérszámfejtés',
                'verbose_name_plural': 'bérszámfejtések',
                'db_table': 'payrolls',
            },
            bases=('viewflow.process', models.Model),
        ),
    ]
