
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-17T11:47:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "64c8bb61e3af19ab0a3b27286d8b357a5f586e2d",
 "version": "v0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
