
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-11T13:43:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ceeee9b68fb8145d41a4be9a74b90bae8740e475",
 "version": "1.0.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
