[tool.poetry]
name = "count-lines"
version = "0.1.1"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]
readme = "README.md"
repository = "https://github.com/eyalev/count-lines"

[tool.poetry.scripts]
count-lines = "count_lines.cli:cli"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
clipboard-util = "^0.1.1"
input-util = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
