[tool.poetry]
name = "blc"
version = "0.1.1"
description = ""
authors = ["Dimitrios Strantsalis <dstrants@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
cleo = "^0.8.1"
tinydb = "^4.1.1"
requests = "^2.23.0"
pendulum = "^2.1.0"
rich = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylama = "^7.7.1"
pylint = "^2.5.2"
autopep8 = "^1.5.3"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
