define([], function() {

    // BASE
    const STRING_NULL = "";

    // WORD
    const STRING_WORD_SIGNUP_KOR = "회원가입";
    const STRING_WORD_LOGIN_KOR = "로그인";
    const STRING_WORD_OR_KOR = "또는";
    const STRING_WORD_TERMS_OF_USE_KOR = "이용약관";
    const STRING_WORD_NECESSARY_KOR = "필수";
    const STRING_WORD_SETTING_KOR = "설정";
    const STRING_WORD_MODIFY_KOR = "수정";
    const STRING_WORD_NOTICE_KOR = "공지사항";

    // PHRASE
    const STRING_PHRASE_ID_SAVED_KOR = "아이디 저장";
    const STRING_PHRASE_APPLE_LOGIN_KOR = "애플계정으로 로그인"; 
    const STRING_PHRASE_KAKAO_LOGIN_KOR = "카카오계정으로 로그인"; 
    const STRING_PHRASE_PROJECT_TITLE = "템플릿 파이썬";

    // MESSAGE
    const STRING_MESSAGE_PLEASE_ENTER_USERNAME_KOR = "이름을 입력해주세요";
    const STRING_MESSAGE_PLEASE_ENTER_EMAIL_KOR = "이메일을 입력해주세요.";
    const STRING_MESSAGE_PLEASE_ENTER_PASSWORD_KOR = "패스워드를 입력해주세요.";
    const STRING_MESSAGE_PLEASE_CHECK_PASSWORD_KOR =  "패스워드를 확인해주세요.";
    const STRING_MESSAGE_NOT_MEMBER_YET_KOR = "아직 회원이 아니신가요?";
    const STRING_MESSAGE_FIND_PASSWORD_KOR = "비밀 번호를 잊으셨나요?";
    const STRING_MESSAGE_I_AGREE_TO_THE_FOLLOWING_KOR = "아래 내용에 모두 동의합니다.";
    const STRING_MESSAGE_EDIT_MY_INFO_KOR = "내 정보를 수정하세요.";
    const STRING_MESSAGE_PLEASE_ENTER_NAME_OF_THE_OPTION_KOR = "찾으시는 시설 이름을 입력하세요.";

    // BACKEND PATH API
    const STRING_BACKEND_PATH_GALLERY = "gallery";
    const STRING_BACKEND_PATH_FACILITY = "facility";
    
    return {
        STRING_NULL,

        STRING_WORD_SIGNUP_KOR,
        STRING_WORD_LOGIN_KOR,
        STRING_WORD_OR_KOR,
        STRING_WORD_TERMS_OF_USE_KOR,
        STRING_WORD_NECESSARY_KOR,
        STRING_WORD_SETTING_KOR,
        STRING_WORD_MODIFY_KOR,
        STRING_WORD_NOTICE_KOR,

        STRING_PHRASE_ID_SAVED_KOR,
        STRING_PHRASE_APPLE_LOGIN_KOR,
        STRING_PHRASE_KAKAO_LOGIN_KOR,
        STRING_PHRASE_PROJECT_TITLE,

        STRING_MESSAGE_PLEASE_ENTER_USERNAME_KOR,
        STRING_MESSAGE_PLEASE_ENTER_EMAIL_KOR,
        STRING_MESSAGE_PLEASE_ENTER_PASSWORD_KOR,
        STRING_MESSAGE_PLEASE_CHECK_PASSWORD_KOR,
        STRING_MESSAGE_NOT_MEMBER_YET_KOR,
        STRING_MESSAGE_FIND_PASSWORD_KOR,
        STRING_MESSAGE_I_AGREE_TO_THE_FOLLOWING_KOR,
        STRING_MESSAGE_EDIT_MY_INFO_KOR,
        STRING_MESSAGE_PLEASE_ENTER_NAME_OF_THE_OPTION_KOR
    }
});