# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sc_msg_questentrance.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_base_pb2 as msg__base__pb2
import msg_common_pb2 as msg__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sc_msg_questentrance.proto',
  package='FunPlus.Common.Config',
  syntax='proto2',
  serialized_options=b'H\001Z\022server/pkg/gen/msg',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asc_msg_questentrance.proto\x12\x15\x46unPlus.Common.Config\x1a\x0emsg_base.proto\x1a\x10msg_common.proto\"$\n\x1aPBQuestEntranceDataRequest:\x06\x80}\x81\xd6\x80\x05\"_\n\x1bPBQuestEntranceDataResponse\x12\x38\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32*.FunPlus.Common.Config.PBQuestEntranceData:\x06\x80}\x82\xd6\x80\x05\x42\x16H\x01Z\x12server/pkg/gen/msg'
  ,
  dependencies=[msg__base__pb2.DESCRIPTOR,msg__common__pb2.DESCRIPTOR,])




_PBQUESTENTRANCEDATAREQUEST = _descriptor.Descriptor(
  name='PBQuestEntranceDataRequest',
  full_name='FunPlus.Common.Config.PBQuestEntranceDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\200}\201\326\200\005',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=123,
)


_PBQUESTENTRANCEDATARESPONSE = _descriptor.Descriptor(
  name='PBQuestEntranceDataResponse',
  full_name='FunPlus.Common.Config.PBQuestEntranceDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='FunPlus.Common.Config.PBQuestEntranceDataResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\200}\202\326\200\005',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=220,
)

_PBQUESTENTRANCEDATARESPONSE.fields_by_name['data'].message_type = msg__common__pb2._PBQUESTENTRANCEDATA
DESCRIPTOR.message_types_by_name['PBQuestEntranceDataRequest'] = _PBQUESTENTRANCEDATAREQUEST
DESCRIPTOR.message_types_by_name['PBQuestEntranceDataResponse'] = _PBQUESTENTRANCEDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PBQuestEntranceDataRequest = _reflection.GeneratedProtocolMessageType('PBQuestEntranceDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _PBQUESTENTRANCEDATAREQUEST,
  '__module__' : 'sc_msg_questentrance_pb2'
  # @@protoc_insertion_point(class_scope:FunPlus.Common.Config.PBQuestEntranceDataRequest)
  })
_sym_db.RegisterMessage(PBQuestEntranceDataRequest)

PBQuestEntranceDataResponse = _reflection.GeneratedProtocolMessageType('PBQuestEntranceDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _PBQUESTENTRANCEDATARESPONSE,
  '__module__' : 'sc_msg_questentrance_pb2'
  # @@protoc_insertion_point(class_scope:FunPlus.Common.Config.PBQuestEntranceDataResponse)
  })
_sym_db.RegisterMessage(PBQuestEntranceDataResponse)


DESCRIPTOR._options = None
_PBQUESTENTRANCEDATAREQUEST._options = None
_PBQUESTENTRANCEDATARESPONSE._options = None
# @@protoc_insertion_point(module_scope)
