[tool.poetry]
name = "gvmkit-build"
version = "0.1.1"
description = ""
authors = ["Przemysław K. Rekucki <prekucki@rcl.pl>"]

[tool.poetry.dependencies]
python = "^3.6"
docker = "^4.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
gvmkit-build = "gvmkit_build:build"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

