# coding: utf-8

"""
    Unofficial Degiro API

    Unofficial Degiro API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: maximdeclercq00@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import degiro_client
from degiro_client.api.reporting_api import ReportingApi  # noqa: E501
from degiro_client.rest import ApiException


class TestReportingApi(unittest.TestCase):
    """ReportingApi unit test stubs"""

    def setUp(self):
        self.api = ReportingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orderhistory(self):
        """Test case for orderhistory

        TODO  # noqa: E501
        """
        pass

    def test_reporting(self):
        """Test case for reporting

        TODO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
