
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-11T22:49:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3287b7e395d1b42aab92e95fbc3aeaf8a228b3c4",
 "version": "0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
