[tool.poetry]
name = "s3-kvs"
version = "0.1.0"
description = "Python wrapper for an AWS S3 backed key-value store."
authors = ["Richard Campen <richard@campen.co>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
