[tool.poetry]
name = "binarysearchtree"
version = "0.2.0"
description = "Binary search tree"
authors = ["Anes Foufa <anes.foufa@upply.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
hypothesis = "^5.16"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
