[tool.poetry]
name = "gilot"
version = "0.1.7"
description = "a git log visual analyzer"
readme = "README.md"
repository = "https://github.com/hirokidaichi/gilot"
authors = ["hirokidaichi <hirokidaichi@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.18.5"
pandas = "^1.0.4"
GitPython = "^3.1.3"
datetime = "^4.3"
seaborn = "^0.10.1"
argparse = "^1.4.0"
matplotlib = "^3.2.1"
python-Levenshtein = "^0.12.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
autopep8 = "^1.5.3"
mypy = "^0.780"
pytest = "^5.4.3"

[tool.poetry.scripts]
gilot = "gilot.app:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

