[tool.poetry]
name = "gvmkit-build"
version = "0.1.3"
description = ""
authors = ["Przemysław K. Rekucki <prekucki@rcl.pl>"]
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Environment :: Console',
    'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
    'Intended Audience :: Developers'
]


[tool.poetry.dependencies]
python = "^3.6"
docker = "^4.2.1"
argparse = "^1.4.0"
alive-progress = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = { version = "^19.10b0", python = "^3.6" }
mypy = "^0.780"

[tool.poetry.scripts]
gvmkit-build = "gvmkit_build:build"

[tool.black]
line-length = 88
include = '\.pyi?$'

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"



