repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length, "100"]
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        language_version: python3
      - id: end-of-file-fixer
        language_version: python3
      - id: check-yaml
        language_version: python3
      - id: debug-statements
        language_version: python3
      - id: flake8
        language_version: python3
        additional_dependencies: [flake8-comprehensions]
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.1
    hooks:
      - id: pyupgrade
        language_version: python3
  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.1
    hooks:
    - id: pydocstyle
  - repo: local
    hooks:
      - id: system-pylint
        name: pylint
        description: pylint hook
        entry: python -m pylint.__main__
        files: \.py$
        language: system
