# Copyright (C) 2018 UCSC Computational Genomics Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The following variables must be specified:
# - vmname
# - resgrp
# - storagename
- name: Remove Virtual Machine and associated objects
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Remove VM and all resources
    azure_rm_virtualmachine:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      state: absent
      remove_on_absent:
         - network_interfaces
         - virtual_storage
         - public_ips

  - name: Delete security group
    azure_rm_securitygroup:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      state: absent

  - name: Delete storage account
    azure_rm_storageaccount:
      resource_group: '{{ resgrp }}'
      name: '{{ storagename }}'
      state: absent

