[tool.poetry]
name = "reinstate-revert-revert"
version = "1.0.0"
description = "pre-commit plugin to improve default commit messages when reverting reverts"
authors = ["Erik Ogan <erik@ogan.net>"]
maintainers = ["Erik Ogan <erik@ogan.net>"]
license = "Mozilla Public License 2.0"
readme = "README.md"
homepage = "https://github.com/erikogan/reinstate-revert-revert"
repository = "https://github.com/erikogan/reinstate-revert-revert"
keywords = [
  "precommit",
  "pre-commit",
  "revert"]

[tool.poetry.dependencies]
python = "^3.7"
dulwich = "^0.19.16"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pytest-mock = "^3.1.0"
flake8 = "^3.8.1"
bump2version = "^1.0.0"

[tool.poetry.scripts]
reinstate-revert-revert = "reinstate_revert_revert.cli:main"

[tool.poetry.urls]
issues = "https://github.com/erikogan/reinstate-revert-revert/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
