# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_base.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
import msg_id_define_pb2 as msg__id__define__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_base.proto',
  package='FunPlus.Common.Config',
  syntax='proto2',
  serialized_options=b'H\001Z\022server/pkg/gen/msg',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emsg_base.proto\x12\x15\x46unPlus.Common.Config\x1a google/protobuf/descriptor.proto\x1a\x13msg_id_define.proto:\\\n\x0fOptionMessageId\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x0f \x01(\x0e\x32!.FunPlus.Common.Config.EMessageIdB\x16H\x01Z\x12server/pkg/gen/msg'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,msg__id__define__pb2.DESCRIPTOR,])


OPTIONMESSAGEID_FIELD_NUMBER = 2000
OptionMessageId = _descriptor.FieldDescriptor(
  name='OptionMessageId', full_name='FunPlus.Common.Config.OptionMessageId', index=0,
  number=2000, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=-1,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['OptionMessageId'] = OptionMessageId
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptionMessageId.enum_type = msg__id__define__pb2._EMESSAGEID
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(OptionMessageId)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
