[build-system]
requires = [
    'setuptools',
    'wheel',
]

[tool.tidypy]
exclude = [
    'docs/source/conf.py',
    'tests/.*',
    'build/.*',
    'dist/.*',
    '.pytest_cache/*',
]
vulture = {use = false}
pydocstyle = {use = false}

[tool.tidypy.pycodestyle]
disabled = [
    'W391',
]

[tool.tidypy.pylint]
disabled = [
    'missing-docstring',
    'trailing-newlines',
    'no-self-use',
    'duplicate-code',
    'consider-using-set-comprehension',
    'useless-object-inheritance',
]
[tool.tidypy.pylint.options]
min-public-methods = 0

[tool.tidypy.pyflakes]
disabled = [
    'UnusedImport',
    'ImportStarUsed',
]

[tool.tidypy.yamllint]
disabled = [
    'empty-lines',
    'document-start',
]

[tool.tidypy.2to3]
disabled = [
    'set_literal',
]

[tool.tidypy.rstlint.options]
sphinx-extensions = [
    'sphinx.ext.autodoc',
]
ignore-directives = [
    'py:exception',
]
ignore-roles = [
    'ref',
]

