image: Visual Studio 2019
cache:
  - .env
  - .cache
  - &omwcmd-ver c:\python38-x64\Scripts\omwcmd-0.2.0.exe
  - &omwcmd c:\python38-x64\Scripts\omwcmd.exe

environment:
  PATH: '%PATH%;c:\python38-x64\Scripts;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts;C:\Program Files\Sandboxie'
  PYTHON: "C:\\Python38-x64"
  OMWCMD_VER: *omwcmd-ver
  OMWCMD: *omwcmd

before_build:
- ps: |
    if (!(Test-Path .cache/SandboxieInstall64-v5.41.0.exe)) {
        New-Item -ItemType Directory -Force -Path .cache
        iwr https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.2/SandboxieInstall64-v5.41.0.exe -OutFile .cache/SandboxieInstall64-v5.41.0.exe
    }
    .cache\SandboxieInstall64-v5.41.0.exe /S /install
    if (!(Test-Path $env:OMWCMD_VER) -Or !(Test-Path $env:OMWCMD)) {
        iwr https://gitlab.com/portmod/omwcmd/uploads/7c4ee7879b2e129152021c43c9fae16d/omwcmd.exe -OutFile $env:OMWCMD_VER
        iwr https://gitlab.com/portmod/omwcmd/uploads/7c4ee7879b2e129152021c43c9fae16d/omwcmd.exe -OutFile $env:OMWCMD
    }

build_script:
- cmd: |
    c:\python38-x64\python.exe -m pip install virtualenv pip --upgrade --user
    virtualenv .venv
    .venv\Scripts\activate
    pip3 install .[test]

test_script:
- cmd: >-
    pytest --cov=portmod --cov=pybuild_
