# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _tubeSegmentConnectedComponentsPython
else:
    import _tubeSegmentConnectedComponentsPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _tubeSegmentConnectedComponentsPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _tubeSegmentConnectedComponentsPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.itkImagePython
import itk.itkPointPython
import itk.vnl_vectorPython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.vnl_matrixPython
import itk.itkFixedArrayPython
import itk.vnl_vector_refPython
import itk.itkVectorPython
import itk.itkSizePython
import itk.ITKCommonBasePython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkMatrixPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
import itk.itkImageRegionPython
import itk.itkRGBPixelPython
import itk.itkRGBAPixelPython
import itk.itkSymmetricSecondRankTensorPython

def tubeSegmentConnectedComponentsSSSS2_New():
    return tubeSegmentConnectedComponentsSSSS2.New()

class tubeSegmentConnectedComponentsSSSS2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsSSSS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsSSSS2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsSSSS2

        Create a new object of the class tubeSegmentConnectedComponentsSSSS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsSSSS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsSSSS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsSSSS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsSSSS2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_swigregister(tubeSegmentConnectedComponentsSSSS2)
tubeSegmentConnectedComponentsSSSS2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2___New_orig__
tubeSegmentConnectedComponentsSSSS2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS2_cast


def tubeSegmentConnectedComponentsSSSS3_New():
    return tubeSegmentConnectedComponentsSSSS3.New()

class tubeSegmentConnectedComponentsSSSS3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsSSSS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsSSSS3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsSSSS3

        Create a new object of the class tubeSegmentConnectedComponentsSSSS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsSSSS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsSSSS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsSSSS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsSSSS3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_swigregister(tubeSegmentConnectedComponentsSSSS3)
tubeSegmentConnectedComponentsSSSS3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3___New_orig__
tubeSegmentConnectedComponentsSSSS3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSSS3_cast


def tubeSegmentConnectedComponentsSSUC2_New():
    return tubeSegmentConnectedComponentsSSUC2.New()

class tubeSegmentConnectedComponentsSSUC2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsSSUC2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsSSUC2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsSSUC2

        Create a new object of the class tubeSegmentConnectedComponentsSSUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsSSUC2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsSSUC2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsSSUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsSSUC2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_swigregister(tubeSegmentConnectedComponentsSSUC2)
tubeSegmentConnectedComponentsSSUC2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2___New_orig__
tubeSegmentConnectedComponentsSSUC2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC2_cast


def tubeSegmentConnectedComponentsSSUC3_New():
    return tubeSegmentConnectedComponentsSSUC3.New()

class tubeSegmentConnectedComponentsSSUC3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsSSUC3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsSSUC3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsSSUC3

        Create a new object of the class tubeSegmentConnectedComponentsSSUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsSSUC3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsSSUC3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsSSUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsSSUC3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_swigregister(tubeSegmentConnectedComponentsSSUC3)
tubeSegmentConnectedComponentsSSUC3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3___New_orig__
tubeSegmentConnectedComponentsSSUC3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUC3_cast


def tubeSegmentConnectedComponentsSSUS2_New():
    return tubeSegmentConnectedComponentsSSUS2.New()

class tubeSegmentConnectedComponentsSSUS2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsSSUS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsSSUS2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsSSUS2

        Create a new object of the class tubeSegmentConnectedComponentsSSUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsSSUS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsSSUS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsSSUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsSSUS2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_swigregister(tubeSegmentConnectedComponentsSSUS2)
tubeSegmentConnectedComponentsSSUS2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2___New_orig__
tubeSegmentConnectedComponentsSSUS2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS2_cast


def tubeSegmentConnectedComponentsSSUS3_New():
    return tubeSegmentConnectedComponentsSSUS3.New()

class tubeSegmentConnectedComponentsSSUS3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsSSUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsSSUS3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsSSUS3

        Create a new object of the class tubeSegmentConnectedComponentsSSUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsSSUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsSSUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsSSUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsSSUS3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_swigregister(tubeSegmentConnectedComponentsSSUS3)
tubeSegmentConnectedComponentsSSUS3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3___New_orig__
tubeSegmentConnectedComponentsSSUS3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsSSUS3_cast


def tubeSegmentConnectedComponentsUCSS2_New():
    return tubeSegmentConnectedComponentsUCSS2.New()

class tubeSegmentConnectedComponentsUCSS2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUCSS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUCSS2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUCSS2

        Create a new object of the class tubeSegmentConnectedComponentsUCSS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUCSS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUCSS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUCSS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUCSS2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_swigregister(tubeSegmentConnectedComponentsUCSS2)
tubeSegmentConnectedComponentsUCSS2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2___New_orig__
tubeSegmentConnectedComponentsUCSS2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS2_cast


def tubeSegmentConnectedComponentsUCSS3_New():
    return tubeSegmentConnectedComponentsUCSS3.New()

class tubeSegmentConnectedComponentsUCSS3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUCSS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUCSS3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUCSS3

        Create a new object of the class tubeSegmentConnectedComponentsUCSS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUCSS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUCSS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUCSS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUCSS3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_swigregister(tubeSegmentConnectedComponentsUCSS3)
tubeSegmentConnectedComponentsUCSS3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3___New_orig__
tubeSegmentConnectedComponentsUCSS3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCSS3_cast


def tubeSegmentConnectedComponentsUCUC2_New():
    return tubeSegmentConnectedComponentsUCUC2.New()

class tubeSegmentConnectedComponentsUCUC2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUCUC2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUCUC2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUCUC2

        Create a new object of the class tubeSegmentConnectedComponentsUCUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUCUC2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUCUC2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUCUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUCUC2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_swigregister(tubeSegmentConnectedComponentsUCUC2)
tubeSegmentConnectedComponentsUCUC2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2___New_orig__
tubeSegmentConnectedComponentsUCUC2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC2_cast


def tubeSegmentConnectedComponentsUCUC3_New():
    return tubeSegmentConnectedComponentsUCUC3.New()

class tubeSegmentConnectedComponentsUCUC3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUCUC3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUCUC3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUCUC3

        Create a new object of the class tubeSegmentConnectedComponentsUCUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUCUC3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUCUC3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUCUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUCUC3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_swigregister(tubeSegmentConnectedComponentsUCUC3)
tubeSegmentConnectedComponentsUCUC3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3___New_orig__
tubeSegmentConnectedComponentsUCUC3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUC3_cast


def tubeSegmentConnectedComponentsUCUS2_New():
    return tubeSegmentConnectedComponentsUCUS2.New()

class tubeSegmentConnectedComponentsUCUS2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUCUS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUCUS2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUCUS2

        Create a new object of the class tubeSegmentConnectedComponentsUCUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUCUS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUCUS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUCUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUCUS2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_swigregister(tubeSegmentConnectedComponentsUCUS2)
tubeSegmentConnectedComponentsUCUS2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2___New_orig__
tubeSegmentConnectedComponentsUCUS2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS2_cast


def tubeSegmentConnectedComponentsUCUS3_New():
    return tubeSegmentConnectedComponentsUCUS3.New()

class tubeSegmentConnectedComponentsUCUS3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUCUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUCUS3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUCUS3

        Create a new object of the class tubeSegmentConnectedComponentsUCUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUCUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUCUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUCUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUCUS3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_swigregister(tubeSegmentConnectedComponentsUCUS3)
tubeSegmentConnectedComponentsUCUS3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3___New_orig__
tubeSegmentConnectedComponentsUCUS3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUCUS3_cast


def tubeSegmentConnectedComponentsUSSS2_New():
    return tubeSegmentConnectedComponentsUSSS2.New()

class tubeSegmentConnectedComponentsUSSS2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUSSS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUSSS2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUSSS2

        Create a new object of the class tubeSegmentConnectedComponentsUSSS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUSSS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUSSS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUSSS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUSSS2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_swigregister(tubeSegmentConnectedComponentsUSSS2)
tubeSegmentConnectedComponentsUSSS2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2___New_orig__
tubeSegmentConnectedComponentsUSSS2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS2_cast


def tubeSegmentConnectedComponentsUSSS3_New():
    return tubeSegmentConnectedComponentsUSSS3.New()

class tubeSegmentConnectedComponentsUSSS3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUSSS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUSSS3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUSSS3

        Create a new object of the class tubeSegmentConnectedComponentsUSSS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUSSS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUSSS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUSSS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUSSS3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_swigregister(tubeSegmentConnectedComponentsUSSS3)
tubeSegmentConnectedComponentsUSSS3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3___New_orig__
tubeSegmentConnectedComponentsUSSS3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSSS3_cast


def tubeSegmentConnectedComponentsUSUC2_New():
    return tubeSegmentConnectedComponentsUSUC2.New()

class tubeSegmentConnectedComponentsUSUC2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUSUC2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUSUC2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUSUC2

        Create a new object of the class tubeSegmentConnectedComponentsUSUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUSUC2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUSUC2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUSUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUSUC2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_swigregister(tubeSegmentConnectedComponentsUSUC2)
tubeSegmentConnectedComponentsUSUC2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2___New_orig__
tubeSegmentConnectedComponentsUSUC2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC2_cast


def tubeSegmentConnectedComponentsUSUC3_New():
    return tubeSegmentConnectedComponentsUSUC3.New()

class tubeSegmentConnectedComponentsUSUC3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUSUC3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUSUC3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUSUC3

        Create a new object of the class tubeSegmentConnectedComponentsUSUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUSUC3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUSUC3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUSUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUSUC3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_swigregister(tubeSegmentConnectedComponentsUSUC3)
tubeSegmentConnectedComponentsUSUC3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3___New_orig__
tubeSegmentConnectedComponentsUSUC3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUC3_cast


def tubeSegmentConnectedComponentsUSUS2_New():
    return tubeSegmentConnectedComponentsUSUS2.New()

class tubeSegmentConnectedComponentsUSUS2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUSUS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUSUS2
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUSUS2

        Create a new object of the class tubeSegmentConnectedComponentsUSUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUSUS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUSUS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUSUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUSUS2 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_swigregister(tubeSegmentConnectedComponentsUSUS2)
tubeSegmentConnectedComponentsUSUS2___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2___New_orig__
tubeSegmentConnectedComponentsUSUS2_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS2_cast


def tubeSegmentConnectedComponentsUSUS3_New():
    return tubeSegmentConnectedComponentsUSUS3.New()

class tubeSegmentConnectedComponentsUSUS3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeSegmentConnectedComponentsUSUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3___New_orig__)
    Clone = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_Clone)
    SetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_SetInput)
    GetInput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_GetInput)
    GetNumberOfComponents = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_GetNumberOfComponents)
    SetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_SetMinimumVolume)
    GetMinimumVolume = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_GetMinimumVolume)
    SetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_SetSeedMask)
    GetSeedMask = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_GetSeedMask)
    GetOutput = _swig_new_instance_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_GetOutput)
    __swig_destroy__ = _tubeSegmentConnectedComponentsPython.delete_tubeSegmentConnectedComponentsUSUS3
    cast = _swig_new_static_method(_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_cast)

    def New(*args, **kargs):
        """New() -> tubeSegmentConnectedComponentsUSUS3

        Create a new object of the class tubeSegmentConnectedComponentsUSUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeSegmentConnectedComponentsUSUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeSegmentConnectedComponentsUSUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeSegmentConnectedComponentsUSUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeSegmentConnectedComponentsUSUS3 in _tubeSegmentConnectedComponentsPython:
_tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_swigregister(tubeSegmentConnectedComponentsUSUS3)
tubeSegmentConnectedComponentsUSUS3___New_orig__ = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3___New_orig__
tubeSegmentConnectedComponentsUSUS3_cast = _tubeSegmentConnectedComponentsPython.tubeSegmentConnectedComponentsUSUS3_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def segment_connected_components(*args, **kwargs):
    """Procedural interface for SegmentConnectedComponents"""
    import itk
    instance = itk.SegmentConnectedComponents.New(*args, **kwargs)
    return instance.__internal_call__()

def segment_connected_components_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.SegmentConnectedComponents, itkTemplate.itkTemplate):
        filter_object = itk.SegmentConnectedComponents.values()[0]
    else:
        filter_object = itk.SegmentConnectedComponents

    segment_connected_components.__doc__ = filter_object.__doc__
    segment_connected_components.__doc__ += "\n Args are Input(s) to the filter.\n"
    segment_connected_components.__doc__ += "Available Keyword Arguments:\n"
    segment_connected_components.__doc__ += "".join([
        "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
        for item in dir(filter_object)
        if item[:3] == "Set"])



