
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-18T13:00:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4271982e9ba55e6249cf79c951ed4c175c0c8b7c",
 "version": "1.2.1-alpha.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
