[tool.poetry]
name = "basicsql"
version = "0.1.4"
description = ""
authors = ["Ramon Brandt <devramon22@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.1"
sqlalchemy = "^1.3.13"
pandas = "^1.0.1"
numpy = "^1.18.1"
jinjasql = "^0.1.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.4.4"
mypy = "^0.761"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
