[tool.poetry]
name = "aurflux"
version = "1.2"
description = "Aurflux!"
authors = ["Zenith <inbox@zenith.dev>"]

[tool.poetry.dependencies]
python = "^3.9"
discord = "*"
aurcore = "*"
toml = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
