[tool.poetry]
name = "pylinalg"
version = "0.1.0"
description = "Linear algebra utilities for Python"
authors = ["Korijn van Golen <korijn@gmail.com>"]
license = "MIT"
homepage = "https://github.com/pygfx/pylinalg"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
flake8 = "^3.8.3"
black = "^19.10b0"
flake8-black = "^0.2.0"
flake8-import-order = "^0.18.1"
flake8-print = "^3.1.4"
pytest-cov = "^2.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

