[tool.poetry]
name = "SandsPythonFunctions"
version = "0.0.1a13"
description = "Functions I use regularly with my python projects"
authors = ["ldsands <ldsands@outlook.com>"]
repository = "https://github.com/ldsands/SandsPythonFunctions"
license = "MIT"
readme = "README.md"
packages = [
    { include = "SandsPythonFunctions", from = "src" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
#python
python = "^3.7"
# data file management and manipulation
numpy = "^1.18.5"
pandas = "^1.0.3"
pyarrow = "^0.16.0"
zstandard = "^0.13.0"
# graphing
altair = "^4.1.0"
altair_saver = "^0.5.0"
matplotlib = "^3.2.1"
# nlp
gensim = "^3.8.3"
nltk = "^3.5"
pyemd = "^0.5.1"
wmd = "^1.3.2"
# jupyter/ipython stuff
notebook = "^6.0.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# [[tool.poetry.source]]
# name = "TestPyPI"
# url = "https://test.pypi.org/legacy/"
# default = true
