{
 "title": "Patching Status",
 "description": "Shows software patch status summary information",
 "tags": [ "patching" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "${VAR_SERVER}" }
  ]
 },
 "panels": [
  {
   "title": "Patches / Platform",
   "type": "grafana-piechart-panel",
   "description": "Total proportion of updates by platform.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_platform) by (platform_name)",
     "legendFormat": "{{platform_name}}"
    }
   ]
  },
  {
   "title": "# Patches",
   "type": "grafana-piechart-panel",
   "description": "Shows software patches grouped by state / progress",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state{state!=\"Unassigned\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "# Patches / Time",
   "type": "graph",
   "description": "Shows the number of devices over time, grouped by their patch status.  You can use this to track progress over time.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state{state!=\"Unassigned\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Top 10 Non Compliant Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_device) by (device_name, device_id)",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Patches",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum(extra_metrics_software_updates_by_update) by (update_name, fw_id))",
     "legendFormat": "{{update_name}}"
    }
   ]
  },
  {
   "title": "# Devices / Health",
   "type": "grafana-piechart-panel",
   "description": "Health summary of devices in the system.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "extra_metrics_per_device_compliance",
     "legendFormat": "{{compliance}}"
    }
   ]
  },
  {
   "title": "Total Critical Updates",
   "type": "singlestat",
   "description": "Shows the total number of critical updates that are waiting to be deployed (or are in progress).",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_device{is_update_critical=\"True\"})"
    }
   ]
  },
  {
   "title": "Total Other Updates",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_device{is_update_critical=\"False\"})"
    }
   ]
  },
  {
   "title": "Devices Affected",
   "type": "singlestat",
   "description": "Shows the number of devices with pending updates (scope of the required updates)",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(extra_metrics_software_updates_by_device)"
    }
   ]
  }
 ]
}