[tool.poetry]
name = "irpf-cei"
version = "2.0.5"
description = "Programa auxiliar gratuito para calcular custos de ações, ETFs e FIIs."
authors = ["Thiago Carvalho D'Ávila <thiagocavila@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/staticdev/irpf-cei"
homepage = "https://github.com/staticdev/irpf-cei"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.3"
click = "^7.1.1"
xlrd = "^1.2.0"
inquirer = "^2.6.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.0"
flake8-bugbear = "^20.1.4"
safety = "^1.8.7"
pytest = "^5.4.3"
codecov = "^2.1.4"
mypy = "^0.780"
coverage = {extras = ["toml"], version = "^5.0.4"}
pytest-mock = "^3.1.1"
pyfakefs = "^4.0.2"
typeguard = "^2.9.1"
reorder-python-imports = "^2.3.1"
pre-commit = "^2.5.1"

[tool.poetry.scripts]
irpf-cei = "irpf_cei.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["irpf_cei"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
