[tool.poetry]
name = "nndict"
version = "1.0.0"
description = "A dict that does not support None entries. Silently deletes entry if updated to null and works recursively."
authors = ["Tiago Santos <tiago.santos@vizidox.com>"]
license = "MIT"
repository = "https://github.com/Morphotech/NeverNoneDict"
keywords = ["NeverNone", "Dict", "NeverNoneDict", "nndict"]
maintainers = ["Sara Pereira <sara.pereira@vizidox.com>",
               "Rita Mariquitos <rita.mariquitos@vizidox.com>",
               "Hieu Le <hieu.le@vizidox.com>"]
classifiers = ["License :: OSI Approved :: MIT License",
               "Programming Language :: Python :: 3"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
tox = "*"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
