[package]
name = "bergkvist-test"
version = "0.2.0"
authors = ["Tobias Bergkvist <tobias@bergkv.ist>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bergkvist_test"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.10.1", features = ["extension-module"] }
numpy = "0.9.0"
