[tool.poetry]
name = "bhoelHelper"
version = "1.2.1"

description = "Misc helper functionalities."

packages = [
    { include = "berhoel" },
]
exclude=["**/.#*.py", "**/#*.py#"]

authors = ["Berthold Höllmann <berthold-gitlab@xn--hllmanns-n4a.de>"]
license = "MIT"

repository = "https://gitlab.com/berhoel/python/bhoelHelper.git"
homepage = "https://python.xn--hllmanns-n4a.de/bhoelHelper/"
documentation = "https://www.xn--hllmanns-n4a.de/python/bhoelHelper/"
readme = "README.rst"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^2.7 || >3.6"
"backports.functools-lru-cache" = {version="^1.6.1", python="<3.3"}
pathlib2 = {version="^2.3.5", python="<3.4"}


[tool.poetry.dev-dependencies]
pytest = [
    {version="^5.4.0", python=">=3.6"},
    {version="^4.6", python="^2.7"}
]
tox = "^3.15.1"
pdbpp = "^0.10.2"
Sphinx = [{version="^3.1.0", python=">=3.6"}]
sphinx-rtd-theme = [{version="^0.4.3", python=">=3.6"}]
blacker = [{ version="^0.1.0", python=">=3.6"}]
flake8 = "^3.8.2"
pylint = [{version="^2.5.2", python=">=3.5"}]
rope = "^0.17.0"
numpydoc = [{version="^1.0.0", python=">=3.6"}]
urllib3 = [{version="*", python=">=3.6"}]

[tool.isort]
multi_line_output = 5
include_trailing_comma = true
use_parentheses = true
indent = '    '
length_sort = true
line_length = 88
use_parantheses = true
balanced_wrapping = true
import_heading_stdlib = 'Standard libraries.'
import_heading_thirdparty = 'Third party libraries.'
known_first_party = ['berhoel']

[flake8]
max-line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
