[tool.poetry]
name = "epot-poetry-test"
version = "0.2.0"
description = ""
authors = ["Etienne Pot <etiennefg.pot@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.plugins."epot-test.test"]
"abc" = "epot_poetry.sub.other:SomeClass"
