[tool.poetry]
name = "hypyp"
version = "0.2.0-a1"
description = "The Hyperscanning Python Pipeline."
readme = "README.md"
authors = [
    "Anaël AYROLLLES <anael.ayrollles@pasteur.fr>",
    "Florence BRUN <florence.brun@pasteur.fr>",
    "Phoebe CHEN <phoebe.chen1117@gmail.com>",
    "Amir DJALOVSKI <amir.djv@gmail.com>",
    "Yann BEAUXIS <dev@yannbeauxis.net>",
    "Suzanne DIKKER <suzanne.dikker@nyu.edu>",
    "Guillaume DUMAS <guillaume.dumas@centraliens.net>"]
license = "BSD-3-Clause"
homepage = "https://github.com/GHFC/HyPyP"
repository = "https://github.com/GHFC/HyPyP"
documentation = "https://hypyp.readthedocs.io"
classifiers=[
    "Development Status :: 3 - Alpha",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: BSD License",
]
keywords=["hyperscanning", "neuroscience", "pipeline", "statistics", "visualization"]

[tool.poetry.dependencies]
python = "^3.6.1"
mne = "^0.20.0"
joblib = "^0.14.1"
scikit-learn = "^0.22.2"
autoreject = "^0.2.1"
matplotlib = "^3.2.1"
pandas = "^1.0.3"
numpy = "^1.18.3"
astropy = "^4.0.1"
meshio = "^4.0.13"
tqdm = "^4.46.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
mkdocs = "^1.1"
mkdocstrings = "^0.10.3"
mkdocs-material = "^5.1.1"
pylint = "^2.4.4"
black = "^19.10b0"
markdown-include = "^0.5.1"
mpl3d = {git = "https://github.com/rougier/matplotlib-3d"}
jupyterlab = "^2.1.4"
widgetsnbextension = "^3.5.1"
ipywidgets = "^7.5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
