[tool.poetry]
name = "kolbos"
version = "0.1.1"
description = ""
authors = ["LooPeKa"]

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]
colorama = "^0.4.3"
vbml = "^0.5.93"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
kolbos = 'kolbos:main'
