[tool.black]
line-length = 88
exclude = '''
  wandb/internal/internal_api.py
| wandb/internal/file_pusher.py
| wandb/internal/file_stream.py
| wandb/internal/stats.py
'''
include = '''
  wandb/sdk/
| wandb/backend/
| wandb/interface/
| wandb/internal/
| wandb/util/
'''
