[tool.poetry]
name = "tudu-cli"
version = "0.1.0"
description = ""
authors = ["Tom Dugan <tom@dugan.email>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
todoist-python = "^8.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
