# coding: utf-8

"""
    IncQuery Server Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.15.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iqs_client
from iqs_client.models.query_fqn_list_with_revision_descriptor import QueryFQNListWithRevisionDescriptor  # noqa: E501
from iqs_client.rest import ApiException


class TestQueryFQNListWithRevisionDescriptor(unittest.TestCase):
    """QueryFQNListWithRevisionDescriptor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryFQNListWithRevisionDescriptor(self):
        """Test QueryFQNListWithRevisionDescriptor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iqs_client.models.query_fqn_list_with_revision_descriptor.QueryFQNListWithRevisionDescriptor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
