# coding: utf-8

"""
    IncQuery Server Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.15.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iqs_client
from iqs_client.models.persisted_revision_details_response import PersistedRevisionDetailsResponse  # noqa: E501
from iqs_client.rest import ApiException


class TestPersistedRevisionDetailsResponse(unittest.TestCase):
    """PersistedRevisionDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersistedRevisionDetailsResponse(self):
        """Test PersistedRevisionDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iqs_client.models.persisted_revision_details_response.PersistedRevisionDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
