version: '3.7'
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./defaults:/etc/nginx/sites-enabled/defaults:ro
      - ./80-server.conf:/etc/nginx/sites-enabled/80-server.conf:ro
      - nginx-static:/usr/share/nginx/html/sites:ro
      - nginx-conf:/etc/nginx/sites-enabled/sites:ro
      - /etc/webserver/dhparams:/dhparams:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/webserver/letsencrypt:/usr/share/nginx/html/letsencrypt:ro
      - /etc/webserver/logs:/var/log/nginx
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
      rollback_config:
        parallelism: 2
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - nginx

volumes:
  nginx-static:
    external: true
  nginx-conf:
    external: true

networks:
  nginx:
    external: true
