
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-12T16:54:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e26db2c93e000fc88f7f7325c91de8b08eff9e52",
 "version": "0.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
