
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-16T16:55:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f1d92476dfe2ac94125b68e4a080e3d7a321d68",
 "version": "0.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
