[tool.poetry]
name = "iscc-service"
version = "0.2.2"
description = "ISCC Web Service API"
license = "MIT"
authors = ["Titusz Pan <tp@py7.de>"]
readme = "README.md"
homepage = "https://iscc.codes/"
repository = "https://github.com/iscc/iscc-service"
documentation = "https://github.com/iscc/iscc-service"
keywords = ["iscc", "media", "identifier", "blockchain", "cli", "generator", "webservice", "api"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Adaptive Technologies",
    "Topic :: Internet",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
    "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: System :: Distributed Computing",
    "Topic :: Text Processing :: Indexing",
]

[tool.poetry.scripts]
isccservice = 'iscc_service.main:run_server'

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.54"
iscc-cli = "^0.9"
uvicorn = "^0.11"
bitstring = "^3.1"
python-multipart = "^0.0.5"
mcrpc = "^2.0"
loguru = "^0.4"
jmespath = "^0.9"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
black = "^19.10b0"

[build-system]
requires = ["poetry==1.0.0"]
build-backend = "poetry.masonry.api"
