codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "simflow/utils/__init__.py"
  - "simflow/utils/data_loader_mnist.py"
  - "simflow/utils/grad_check_utils.py"
  - "simflow/utils/im2col.py"
