# general
pip

# jupyterhub/jupyterlab
nb_conda_kernels
ipython > 7
jupyter-server-proxy
jupyterlab-git
ipywidgets
jupyterlab < 2.0
jupyter_client < 6.0
jupyter_console
jupyterhub
nodejs
nbconvert
nbval
dask_labextension

# viz tools
panel
param
python-graphviz

# testing, docs, linting
pytest
hypothesis
flake8
sphinx
pytest-cov
black
isort
importnb
