[tool.poetry]
name = "riordinato"
version = "0.1.0"
description = ""
authors = ["Dan- <misternutel@gmail.com>"]
readme = "README.md"
license = "MIT"
keywords = ["organize", "riordinato", "prefixes", "dir"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
