title: "DrOpt"
logo: "/assets/images/logo3.svg"
style: "/assets/css/styles.css"

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
