---
# Deployment:
# Defines whether the environment created for the system should be
# `local` or `production`.
# `local` -> Deployable using `minikube`. Uses the host VM file system
#            for sharing information between workflow steps. Also uses
#            local docker images instead of remote ones for speeding
#            up the development.
# `prod`  -> Deployable on the CERN OpenStack Kubernetes cluster using
#            real distributed file system and images from a docker
#            registry.
DEPLOYMENT: local
IMAGE_PULL_POLICY: IfNotPresent
