stages:
  - Run Job
  - Upload Data

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "api"

run-job:
  stage: Run Job
  image: <DOCKER_IMAGE>
  tags:
    - csiro-swarm
  variables:
    TZ: Australia/Perth
    JOB_PARAMETERS: <PARAMS_JSON>
    FILE_REFS: <FILE_REFS_JSON>
    MODULE_NAME: <MODULE_NAME>
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_CPU_LIMIT: 4
    KUBERNETES_MEMORY_REQUEST: 2Gi
    KUBERNETES_MEMORY_LIMIT: 8Gi
  script:
    - $MODULE_NAME run-job --params-json "$JOB_PARAMETERS" --files-json "$FILE_REFS" --input input --output "output"
    - ls output
  artifacts:
    paths:
      - output/*
    expire_in: 1 week
